### ISSUE TITLE
move to .csproj project format

### ISSUE THREAD

**Issue by FelschR** [FelschR/AspNetCore.Identity.DocumentDB#14]
Beginning with Visual Studio 2017 the old project.json + .xproj format will not be supported anymore.
Using .csproj for .NET Core projects will be the new standard. It's already used by the classic .NET Framework and will add more compatibility between .NET Framework and .NET Core.
Especially referencing libraries (e.g. .NET Standard libraries) will be much easier.

The new format is not backwards compatible, though.

In addition to the migration the following changes have to be made:
- [x] Change git tag creation in appveyor.yml
- [ ] https://github.com/dotnet/cli/issues/5168 needs to be fixed
  - [x] fix this by adapting the build script (workaround)
- [x] #17 migrate nunit tests to xunit
  - [ ] https://github.com/nunit/dotnet-test-nunit/issues/91 nunit support missing
- [ ] update build.bat (or delete?)

**Comment by FelschR** [comment]
The migration was successfully done in new "csproj" branch:
bd6296ea197c90db7b731411fd04c90237ad27f5

AppVeyor support is currently not given.

**Comment by FelschR** [comment]
Current build is failing due to bug in current cli tooling (https://github.com/dotnet/cli/issues/5168).
Could be fixed by adapting the build script but the final cli release will probably fix this anyways.

**Comment by FelschR** [comment]
Adapted AppVeyor build script to add support.
[Latest build](https://ci.appveyor.com/project/FelschR/aspnetcore-identity-documentdb/build/0.2.1-beta-188834363) was successful.

**Comment by FelschR** [comment]
Although the project was migrated a while ago I'll keep this issue open to track status on some issues that required workarounds.
